import React from 'react';
import { ArticleLayout } from '@/components/ArticleLayout';

export default function Page() {
  return (
    <ArticleLayout
      eyebrow="PILLAR C CLUSTER · COMPLIANCE"
      title="ABA Formal Opinion 512 explained for PI firms"
      author="Andy Norman"
      date="28 MAY 2026"
      tldr={
        <>
          <p className="mb-2">In July 2024, the ABA issued Formal Opinion 512, establishing national guidelines for generative AI in legal practice.</p>
          <p className="m-0">For personal injury intake, the core takeaway is the duty of competence, confidentiality, and necessary disclosure when an AI interacts directly with clients.</p>
        </>
      }
    >
      <h2>The ABA takes a stance on AI</h2>
      <p>
        For years, state bars operated in a gray area regarding Artificial Intelligence. With the release of ABA Formal Opinion 512, there is now a clear national framework. The opinion does not ban AI; in fact, it recognizes its immense utility. But it imposes strict ethical guardrails.
      </p>

      <h2>Key Takeaway 1: The Duty of Confidentiality</h2>
      <p>
        The ABA explicitly warns lawyers against feeding client data into "self-learning" AI tools that lack strict confidentiality barriers. If an AI tool uses your prompts to train its broader model, you are violating Rule 1.6 (Confidentiality of Information). 
      </p>
      <p>
        <em>Action item:</em> Ensure any intake vendor explicitly contractually forbids the use of your firm's data for model training.
      </p>

      <h2>Key Takeaway 2: The Duty to Disclose</h2>
      <p>
        Does a law firm have to tell a caller they are speaking to an AI? According to the ABA, if the AI is performing a task that a client would reasonably assume is being done by a human (and the distinction matters), disclosure is required.
      </p>
      <p>
        In the context of voice AI answering the phone, deceiving a caller into thinking they are speaking to a human paralegal is both unethical under the ABA framework and highly detrimental to the firm's brand trust if the caller figures it out.
      </p>

      <h2>Key Takeaway 3: Managerial Responsibility</h2>
      <p>
        Lawyers cannot blindly trust AI outputs. Under Rule 5.3, lawyers have a duty to supervise nonlawyer assistance—and the ABA clarifies that this includes AI tools. You are responsible for ensuring the AI's intake summary accurately reflects the transcript.
      </p>

      <h2>How Della complies with Opinion 512</h2>
      <p>
        Call Della was architected with Opinion 512 in mind. 
      </p>
      <ul>
        <li><strong>Disclosure:</strong> Della immediately identifies herself as the firm's "AI intake specialist." We do not support deceptive voice configurations.</li>
        <li><strong>Confidentiality:</strong> We operate strictly on enterprise-grade APIs with zero-data-retention agreements. Your data never trains public models.</li>
        <li><strong>Supervision:</strong> Every dossier generated by Della includes the raw audio file and a verbatim transcript, allowing your attorneys to independently verify the AI's summary against the source material in seconds.</li>
      </ul>
    </ArticleLayout>
  );
}
